language: ruby

services:
  - mongodb
  - docker

before_install:
  - docker build --tag login .
  - docker run -v `pwd`:/srv/host login /bin/sh -c "cp /srv/host/config.json.travis /srv/www/config.json && gulp test"

script:
  - docker ps -a

branches:
  only:
    - master
    - production

notifications:
  slack: wrioos:XDZWFBrf9TDtoEOcw5YGBM4a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$(git log -1 --format='%an')" == "Alexey Anshakov" ]; then npm run bumpVersion; fi

deploy:
  - provider: s3
    access_key_id:
      secure: mR+kXkYTSLM50ICSs7Fm29iFpJo8jCsyYKiyF8ZlBhzmSP8GoHpcsSWd6J/HFnW1WQqa6vAmv/Sxd1Lr23AnxtKyGm+ROej2QQWrp2EouHLEFxuOwy2whLDqAvQcyZyi4eRqeWicAFhM/qrkK4EdvgbsgBqXIY9RXEH1y6Hgxi4=
    secret_access_key:
      secure: G3QfqVMapeaGxersv8Oumdc9QWSnCNmq70hJNmD8OrFgOhKj7F48+uv9WLoBAJxw31WIBBWqMSY9l7CO3ur9plPwL+Gfda7yGUE8HDBMJ/pukL2DAzwd1pu/iPlt/+HMO4YYIDJZsDpSWN5PvxAf+MtsG7hXJUlJSy/nwpvpZ3M=
    bucket: dev.wrioos.com
    upload-dir: Titter-WRIO-App
    acl: public_read
    on:
      branch: master

